# Generated by Django 2.2 on 2019-08-14 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_auto_20190811_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='age',
        ),
        migrations.AddField(
            model_name='emp',
            name='user',
            field=models.OneToOneField(default=models.CharField(max_length=200), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
