# Generated by Django 2.2 on 2019-08-14 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_remove_emp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='emp_dept',
            field=models.ForeignKey(default='not specified', on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
        migrations.AddField(
            model_name='emp',
            name='user',
            field=models.OneToOneField(default=models.CharField(max_length=200), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
